
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 20/09/2023 10:07:50.
      
      Project "D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\3.27.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        D:\\Microsoft\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\Microsoft\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\3.27.5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\Microsoft\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\3.27.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:05.20
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/3.27.5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Futurevox/cmake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/CMakeScratch/TryCompile-txwgbp"
      binary: "D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/CMakeScratch/TryCompile-txwgbp"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/CMakeScratch/TryCompile-txwgbp'
        
        Run Build Command(s): "D:/Microsoft/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_11adb.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 20/09/2023 10:07:56.
        
        Project "D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\CMakeScratch\\TryCompile-txwgbp\\cmTC_11adb.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_11adb.dir\\Debug\\".
          Creating directory "D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\CMakeScratch\\TryCompile-txwgbp\\Debug\\".
          Creating directory "cmTC_11adb.dir\\Debug\\cmTC_11adb.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_11adb.dir\\Debug\\cmTC_11adb.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_11adb.dir\\Debug\\cmTC_11adb.tlog\\unsuccessfulbuild".
        ClCompile:
          D:\\Microsoft\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_11adb.dir\\Debug\\\\" /Fd"cmTC_11adb.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\Futurevox\\cmake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_11adb.dir\\Debug\\\\" /Fd"cmTC_11adb.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\Futurevox\\cmake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\Microsoft\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\CMakeScratch\\TryCompile-txwgbp\\Debug\\cmTC_11adb.exe" /INCREMENTAL /ILK:"cmTC_11adb.dir\\Debug\\cmTC_11adb.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/CMakeScratch/TryCompile-txwgbp/Debug/cmTC_11adb.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Futurevox/fvox_qml/Futurevox/build-cmake/CMakeFiles/CMakeScratch/TryCompile-txwgbp/Debug/cmTC_11adb.lib" /MACHINE:X64  /machine:x64 cmTC_11adb.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_11adb.vcxproj -> D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\CMakeScratch\\TryCompile-txwgbp\\Debug\\cmTC_11adb.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_11adb.dir\\Debug\\cmTC_11adb.tlog\\unsuccessfulbuild".
          Touching "cmTC_11adb.dir\\Debug\\cmTC_11adb.tlog\\cmTC_11adb.lastbuildstate".
        Done Building Project "D:\\Futurevox\\fvox_qml\\Futurevox\\build-cmake\\CMakeFiles\\CMakeScratch\\TryCompile-txwgbp\\cmTC_11adb.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:03.84
        
      exitCode: 0
...
